ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}

#FROM docker.elastic.co/beats/filebeat:8.2.3
#COPY filebeat.yml /usr/share/filebeat/filebeat.yml

#sudo sysctl -w vm.max_map_count=262144
#/sbin/sysctl vm.max_map_count