FROM mcr.microsoft.com/dotnet/sdk:8.0

# copy source
WORKDIR /NetCore
COPY WebApi ./WebApi
COPY WebApi.Tests.API ./WebApi.Tests.API

# run tests
WORKDIR /NetCore/WebApi.Tests.API
ENTRYPOINT ["dotnet", "test", "-v=normal"]
