
#version: '3.8'

########## Extension fields ##########

x-logging:
  &graylog-logging
  driver: syslog
  options:
    syslog-address: ${FP_GRAYLOG_SYSLOG_INPUT}
    syslog-tls-ca-cert: /home/ec2-user/full-plate/nginx/certbot/own_ca_certs/ca_root_cert.pem
    tag: "${HOSTNAME}<|>{{.Name}}"

########## Services ##########
services:

  ########## frontend ##########
  nginx:
    container_name: nginx
    profiles:
      - frontend
    build:
      context: ../webapp
      dockerfile: Dockerfile.aws-front
    environment:
      - NGINX_DOMAIN_NAME=${FP_DOMAIN_NAME:-fullplate.local}
      - NGINX_PROXY_WEBAPI=${FP_PROXY_WEBAPI:-localhost}
      - NGINX_PROXY_GRAYLOG=${FP_PROXY_GRAYLOG:-localhost}
      - NGINX_PROXY_GRAFANA=${FP_PROXY_GRAFANA:-localhost}
      - NGINX_PROXY_KEYCLOAK=${FP_PROXY_KEYCLOAK:-fullplate.local}
      - NGINX_PROXY_PORTAINER=${FP_PROXY_PORTAINER:-fullplate.local}
      - NGINX_ADMIN_IP=${FP_ADMIN_IP:-127.0.0.1}
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ../nginx/templates:/etc/nginx/templates
      - ../nginx/certbot/www/:/var/www/certbot/:ro
      - ../nginx/certbot/letsencrypt/:/etc/letsencrypt/:ro
      - ../nginx/certbot/own_ca_certs:/own_ca_certs:ro
    network_mode: "host"
    logging: *graylog-logging

  certbot:
    container_name: certbot
    build:
      context: ../nginx/certbot
    profiles:
      - certbot
    environment:
      - CERTBOT_DOMAIN_NAME=${FP_DOMAIN_NAME:-fullplate.local}
    volumes:
      - ../nginx/certbot/www/:/var/www/certbot/:rw
      - ../nginx/certbot/letsencrypt/:/etc/letsencrypt/:rw
    network_mode: "host"
    logging: *graylog-logging

  ########## prometheus ##########
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    profiles:
      - exporters
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '-port=28080'
    network_mode: "host"
    logging: *graylog-logging

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    container_name: node_exporter
    profiles:
      - exporters
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=:29100'
    pid: host
    network_mode: "host"
    logging: *graylog-logging

  ########## portainer ###########
  portainer-agent:
    image: portainer/agent:2.21.1
    container_name: portainer-agent
    profiles:
      - portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - ../portainer/agent/data:/data
      - ../nginx/certbot/own_ca_certs:/own_ca_certs:ro
    environment:
      # - EDGE=1
      # - EDGE_ID=${FP_PORTAINER_AGENT_EDGE_ID}
      # - EDGE_KEY=${FP_PORTAINER_AGENT_EDGE_KEY}
      # - EDGE_INSECURE_POLL=0
      - SSL_CERT_FILE=/own_ca_certs/ca_root_cert.crt
      - SSL_CERT_DIR=/own_ca_certs/
    # command:
      # --sslcert /own_ca_certs/${FP_OWN_CA_DOMAIN_NAME:-fullplate.local}.crt
      # --sslkey /own_ca_certs/${FP_OWN_CA_DOMAIN_NAME:-fullplate.local}.key
      # --name portainer_edge_agent
    network_mode: "host"
    logging: *graylog-logging
