scrape_configs:
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:28080
  - job_name: node_exporter
    scrape_interval: 15s
    static_configs:
      - targets:
          - localhost:29100
