name: webapi

on:
  push:
    branches: [ "main" ]

jobs:

  webapi-test-job:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./compose
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run functional tests
        run: docker compose --profile api-tests up --build --abort-on-container-exit

  e2e-test-job:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./compose
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Run end-to-end tests
        run: docker compose --profile e2e-tests up --build --abort-on-container-exit
        env:
          FP_DATABASE_CONNECTION_STRING_NAME: e2e_test_db
          FP_PROXY_HTTP_PORT: 11080
          FP_EMAIL_SERVICE: FakeAwsSesService

  deploy-job:
    runs-on: fx-6300
    needs:
      - webapi-test-job
      - e2e-test-job
    steps:
      - run: git stash push --include-untracked
        working-directory: /home/dmitry/projects/full-plate
      - run: git stash clear
        working-directory: /home/dmitry/projects/full-plate
      - name: Update local repository
        run: git pull
        working-directory: /home/dmitry/projects/full-plate
      - name: Install React app dependencies
        run: npm install
        working-directory: /home/dmitry/projects/full-plate/webapp/react
      - name: Build React app
        run: npm run build
        working-directory: /home/dmitry/projects/full-plate/webapp/react
      - name: Deploy React app
        run: ./deploy-react.sh
        working-directory: /home/dmitry/projects/full-plate/infra
      - name: Build and restart backend containers
        run: sudo systemctl restart backend
